export const INIT_ELEMENTS = "INIT_ELEMENTS";
export const SET_ELEMENTS = "SET_ELEMENTS";
export const CHANGE_OBJECTS_PROPERTIES = "CHANGE_OBJECTS_PROPERTIES";
export const SELECT_OBJECTS = "SELECT_OBJECTS";
export const ADD_OBJECTS = "ADD_OBJECTS";
export const REMOVE_OBJECTS = "REMOVE_OBJECTS";
export const REPLACE_OBJECTS = "REPLACE_OBJECTS";
export const CLEAR_OBJECTS = "CLEAR_OBJECTS";
export const SET_TOOL = "SET_TOOL";


export const BEGIN_EDIT = "BEGIN_EDIT";
export const END_EDIT = "END_EDIT";